services:
  json-server:
    image: node:23-alpine3.20
    working_dir: /
    volumes:
      - ./db.json:/db.json
    command: sh -c "npx json-server --watch db.json --host 0.0.0.0 --port 3000"
    ports:
      - "3000:3000"

  angular:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - json-server
