name: Docker Image CI

on:
  workflow_dispatch:

  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Docker login
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: hubatrifusz
        password: ${{ secrets.GHCR_TOKEN }}
    
    - name: Build the Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/hubatrifusz/slag:latest
        
